CREATE TABLE book_author
(
    book_author_id   INTEGER      NOT NULL,
    book_author_name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_book_author PRIMARY KEY (book_author_id)
);

ALTER TABLE book_author
    ADD CONSTRAINT uc_book_author_book_author_name UNIQUE (book_author_name);

CREATE TABLE book_genre
(
    book_genre_id   INTEGER      NOT NULL,
    book_genre_name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_book_genre PRIMARY KEY (book_genre_id)
);

ALTER TABLE book_genre
    ADD CONSTRAINT uc_book_genre_book_genre_name UNIQUE (book_genre_name);

CREATE TABLE book_publisher
(
    book_publisher_id   INTEGER      NOT NULL,
    book_publisher_name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_book_publisher PRIMARY KEY (book_publisher_id)
);

ALTER TABLE book_publisher
    ADD CONSTRAINT uc_book_publisher_book_publisher_name UNIQUE (book_publisher_name);

CREATE TABLE book_location_floor
(
    book_location_floor_id     INTEGER NOT NULL,
    book_location_floor_number INTEGER NOT NULL,
    CONSTRAINT pk_book_location_floor PRIMARY KEY (book_location_floor_id)
);

ALTER TABLE book_location_floor
    ADD CONSTRAINT uc_book_location_floor_book_location_floor_number UNIQUE (book_location_floor_number);

CREATE TABLE book_location_shelf
(
    book_location_shelf_id     INTEGER NOT NULL,
    book_location_shelf_number INTEGER NOT NULL,
    CONSTRAINT pk_book_location_shelf PRIMARY KEY (book_location_shelf_id)
);

ALTER TABLE book_location_shelf
    ADD CONSTRAINT uc_book_location_shelf_book_location_shelf_number UNIQUE (book_location_shelf_number);

CREATE TABLE city
(
    city_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name TEXT                                     NOT NULL,
    CONSTRAINT pk_city PRIMARY KEY (city_id)
);

CREATE TABLE country
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name TEXT                                     NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE event_type
(
    event_type_id   INTEGER      NOT NULL,
    event_type_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_event_type PRIMARY KEY (event_type_id)
);

ALTER TABLE event_type
    ADD CONSTRAINT uc_event_type_event_type_name UNIQUE (event_type_name);

CREATE TABLE street
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street TEXT                                     NOT NULL,
    CONSTRAINT pk_street PRIMARY KEY (id)
);

CREATE TABLE town
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    town_name TEXT                                     NOT NULL,
    CONSTRAINT pk_town PRIMARY KEY (id)
);

CREATE TABLE zip
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zip_code TEXT                                     NOT NULL,
    CONSTRAINT pk_zip PRIMARY KEY (id)
);

CREATE TABLE book
(
    isbn              VARCHAR(13) NOT NULL,
    book_title        VARCHAR(255) NOT NULL,
    book_genre_id     INTEGER      NOT NULL,
    book_publisher_id INTEGER      NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (isbn)
);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_BOOK_GENRE FOREIGN KEY (book_genre_id) REFERENCES book_genre (book_genre_id);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_BOOK_PUBLISHER FOREIGN KEY (book_publisher_id) REFERENCES book_publisher (book_publisher_id);

CREATE TABLE book_location
(
    book_location_id       INTEGER NOT NULL,
    book_location_floor_id INTEGER NOT NULL,
    book_location_shelf_id INTEGER NOT NULL,
    CONSTRAINT pk_book_location PRIMARY KEY (book_location_id)
);

ALTER TABLE book_location
    ADD CONSTRAINT FK_BOOK_LOCATION_ON_BOOK_LOCATION_FLOOR FOREIGN KEY (book_location_floor_id) REFERENCES book_location_floor (book_location_floor_id);

ALTER TABLE book_location
    ADD CONSTRAINT FK_BOOK_LOCATION_ON_BOOK_LOCATION_SHELF FOREIGN KEY (book_location_shelf_id) REFERENCES book_location_shelf (book_location_shelf_id);

CREATE TABLE customer
(
    customer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(60)                              NOT NULL,
    last_name    VARCHAR(60)                              NOT NULL,
    country_id   INTEGER                                  NOT NULL,
    city_id      INTEGER                                  NOT NULL,
    zip_id       INTEGER                                  NOT NULL,
    town_id      INTEGER                                  NOT NULL,
    street_id    INTEGER,
    streetnumber VARCHAR(15),
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_CITY FOREIGN KEY (city_id) REFERENCES city (city_id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_STREET FOREIGN KEY (street_id) REFERENCES street (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_TOWN FOREIGN KEY (town_id) REFERENCES town (id);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_ZIP FOREIGN KEY (zip_id) REFERENCES zip (id);

CREATE TABLE event
(
    event_id           INTEGER                     NOT NULL,
    event_name         VARCHAR(255)                NOT NULL,
    event_starts_at_ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_type_id      INTEGER                     NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_EVENT_TYPE FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id);

CREATE TABLE author_book_map
(
    book_author_id INTEGER      NOT NULL,
    isbn           VARCHAR(13) NOT NULL,
    CONSTRAINT pk_author_book_map PRIMARY KEY (book_author_id, isbn)
);

ALTER TABLE author_book_map
    ADD CONSTRAINT fk_autboomap_on_book FOREIGN KEY (isbn) REFERENCES book (isbn);

ALTER TABLE author_book_map
    ADD CONSTRAINT fk_autboomap_on_book_author FOREIGN KEY (book_author_id) REFERENCES book_author (book_author_id);

CREATE TABLE book_stock_log
(
    book_stock_log_id INTEGER      NOT NULL,
    book_is_in_stock  BOOLEAN      NOT NULL,
    isbn              VARCHAR(13) NOT NULL,
    book_location_id  INTEGER      NOT NULL,
    CONSTRAINT pk_book_stock_log PRIMARY KEY (book_stock_log_id)
);

ALTER TABLE book_stock_log
    ADD CONSTRAINT FK_BOOK_STOCK_LOG_ON_BOOK_LOCATION FOREIGN KEY (book_location_id) REFERENCES book_location (book_location_id);

ALTER TABLE book_stock_log
    ADD CONSTRAINT FK_BOOK_STOCK_LOG_ON_ISBN FOREIGN KEY (isbn) REFERENCES book (isbn);

CREATE TABLE CustomerCard
(
    customer_card_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id      INTEGER                                  NOT NULL,
    CONSTRAINT pk_customercard PRIMARY KEY (customer_card_id)
);

ALTER TABLE CustomerCard
    ADD CONSTRAINT uc_customercard_customer UNIQUE (customer_id);

ALTER TABLE CustomerCard
    ADD CONSTRAINT FK_CUSTOMERCARD_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

CREATE TABLE customer_event_map
(
    customer_id INTEGER NOT NULL,
    event_id    INTEGER NOT NULL,
    CONSTRAINT pk_customer_event_map PRIMARY KEY (customer_id, event_id)
);

ALTER TABLE customer_event_map
    ADD CONSTRAINT FK_CUSTOMER_EVENT_MAP_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE customer_event_map
    ADD CONSTRAINT FK_CUSTOMER_EVENT_MAP_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (event_id);

CREATE TABLE book_event_map
(
    book_event_id INTEGER      NOT NULL,
    isbn          VARCHAR(13) NOT NULL,
    CONSTRAINT pk_book_event_map PRIMARY KEY (book_event_id, isbn)
);

ALTER TABLE book_event_map
    ADD CONSTRAINT fk_booevemap_on_book FOREIGN KEY (isbn) REFERENCES book (isbn);

ALTER TABLE book_event_map
    ADD CONSTRAINT fk_booevemap_on_event FOREIGN KEY (book_event_id) REFERENCES event (event_id);

CREATE TABLE book_circulation_log
(
    book_circulation_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_starts_at_date     date                                     NOT NULL,
    loan_ends_at_date       date,
    book_returned_at_date   date,
    customer_id             INTEGER                                  NOT NULL,
    fk_stockid              INTEGER,
    CONSTRAINT pk_book_circulation_log PRIMARY KEY (book_circulation_log_id)
);

ALTER TABLE book_circulation_log
    ADD CONSTRAINT FK_BOOK_CIRCULATION_LOG_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE book_circulation_log
    ADD CONSTRAINT FK_BOOK_CIRCULATION_LOG_ON_FK_STOCKID FOREIGN KEY (fk_stockid) REFERENCES book_stock_log (book_stock_log_id);

commit;

